"
I represent an comment on the request.

Public API and Key Messages

- value
- value:

    Instance Variables
	value:		<String>

"
Class {
	#name : #GQLComment,
	#superclass : #GQLAbstractNode,
	#instVars : [
		'value'
	],
	#category : #'GraphQLBeta-Nodes'
}

{ #category : #accessing }
GQLComment >> value [ 
	^ value
]

{ #category : #accessing }
GQLComment >> value: anObject [
	value := anObject
]
