"
I represent an exception of evaluation on graphql, I'm only called if the GQLTypeValidator has a problem with visiting the parts of the document.

Public API and Key Messages

- node      
- node: 
- signal

    Instance Variables
	node:		<GQLNode>

GQLEvaluationException new 
			node: aGQLArgumentNode; 
			signal
"
Class {
	#name : #GQLEvaluationException,
	#superclass : #GQLException,
	#category : #'GraphQLBeta-Core'
}
